### PR TITLE
Base layout

### PR DESCRIPTION
**Pull request by kishkoigor**

### CODE REVIEW

**Comment by valar999** [comment]
How to check this base layout?
`pages/Home.js` don't use `Header`, `Footer` and `Layout`

**Comment by kishkoigor** [comment]
> How to check this base layout? `pages/Home.js` don't use `Header`, `Footer` and `Layout`

So now you can)
Added dummy Homepage

**Comment by valar999** [comment]
Please don't forget to fix layout problems for mobile phones.

**Comment by kishkoigor** [comment]
@valar999 done!

**Review by valar999 — APPROVED** [review]

**Pull request merged**
